import type { Metadata } from 'next';
import Link from 'next/link';
import { PiArrowRight } from 'react-icons/pi';
import NavSection from '@/components/sections/section-02-nav';
import FooterSection from '@/components/sections/section-12-footer';
import { buildAlternates, localizedUrl, toLocale } from '@/lib/seo';
import { getDictionary } from '@/dictionaries';

const copy = { es: { title: 'Creamos el sitio web que tu negocio merece', intro: 'Tu sitio web es la puerta de entrada a nuevos clientes. Lo construimos rápido, moderno y optimizado para que te encuentren en Google.', section: 'Por qué elegirnos para tu proyecto web', faq: 'Preguntas frecuentes', cta: '¿Listo para tener una web que venda?', ctaText: 'Contanos tu proyecto y te enviamos una propuesta en menos de 24 horas.', primary: 'Pedir presupuesto gratis', secondary: 'Ver proyectos', items: [['Velocidad que tus clientes notan', 'Un sitio lento hace que la gente se vaya. Los nuestros cargan al instante en cualquier dispositivo.'], ['Se ve bien en todos lados', 'Diseñamos para celular, tablet y computadora, sin pantallas rotas.'], ['Listo para Google', 'Configuramos lo necesario para que Google encuentre tu sitio.'], ['Seguro y sin complicaciones', 'Código limpio y moderno, sin plugins frágiles ni sitios que se caen.']], faqs: [['¿Cuánto tarda tener mi sitio listo?', 'Una landing suele estar lista en 2 a 3 semanas. Te damos fechas concretas desde el primer día.'], ['¿Cuánto cuesta un sitio web?', 'Los proyectos arrancan desde USD 300 para una landing optimizada.'], ['¿Trabajan de forma remota?', 'Sí, trabajamos con clientes de toda Argentina y del exterior.']] }, en: { title: 'We build the website your business deserves', intro: 'Your website is the gateway to new customers. We build it fast, modern and optimized so people can find you on Google.', section: 'Why choose us for your web project', faq: 'Frequently asked questions', cta: 'Ready for a website that sells?', ctaText: 'Tell us about your project and we will send a proposal within 24 hours.', primary: 'Get a free quote', secondary: 'View projects', items: [['Speed your customers notice', 'A slow site drives people away. Ours load quickly on every device.'], ['Looks great everywhere', 'We design for phones, tablets and desktops without broken screens.'], ['Ready for Google', 'We configure what Google needs to find and understand your site.'], ['Secure and uncomplicated', 'Clean, modern code without fragile plugins or sites that go down.']], faqs: [['How long does a website take?', 'A landing page usually takes 2 to 3 weeks. You get clear dates from day one.'], ['How much does a website cost?', 'Projects start at USD 300 for an optimized landing page.'], ['Do you work remotely?', 'Yes, we work with clients across Argentina and abroad.']] } } as const;

export async function generateMetadata({ params }: { params: { lang: string } }): Promise<Metadata> { const locale = toLocale(params.lang); const c = copy[locale]; return { title: `${c.title} | UpCoded`, description: c.intro, alternates: buildAlternates(locale, 'servicios/desarrollo-web-argentina'), openGraph: { title: c.title, description: c.intro, url: localizedUrl(locale, 'servicios/desarrollo-web-argentina') } }; }
export default async function DesarrolloWebPage({ params }: { params: { lang: 'es' | 'en' } }) { const c = copy[params.lang]; const d = await getDictionary(params.lang); const base = `/${params.lang}`; return <><NavSection dict={d.nav} lang={params.lang} /><main id="contenido" className="pt-[68px]"><section className="mx-auto max-w-container-max px-margin-mobile py-24 md:px-margin-desktop"><nav className="mb-6 flex gap-2 font-mono text-label-caps uppercase text-on-surface-variant"><Link href={base}>{d.common.home}</Link><span>/</span><Link href={`${base}/#servicios`}>{d.common.services}</Link></nav><h1 className="mb-6 max-w-3xl text-display-lg text-on-surface">{c.title}</h1><p className="mb-8 max-w-2xl text-body-md text-on-surface-variant">{c.intro}</p><div className="flex flex-wrap gap-4"><Link href={`${base}/#contacto`} className="inline-flex min-h-[52px] items-center gap-2 rounded-md bg-primary px-7 text-base text-on-primary">{c.primary}<PiArrowRight size={16} /></Link><Link href={`${base}/#portfolio`} className="inline-flex min-h-[52px] items-center rounded-md border border-outline-strong px-7 text-base text-on-surface">{c.secondary}</Link></div></section><section className="border-y border-outline-variant bg-surface-container-low py-24"><div className="mx-auto max-w-container-max px-margin-mobile md:px-margin-desktop"><h2 className="mb-16 text-headline-lg text-on-surface">{c.section}</h2><div className="grid grid-cols-1 gap-6 md:grid-cols-2">{c.items.map(([t, x]) => <div key={t} className="rounded-lg border border-outline-variant bg-surface-container p-7"><h3 className="mb-2 text-headline-md text-on-surface">{t}</h3><p className="text-on-surface-variant">{x}</p></div>)}</div></div></section><section className="mx-auto max-w-container-max px-margin-mobile py-24 md:px-margin-desktop"><h2 className="mb-16 text-headline-lg text-on-surface">{c.faq}</h2><div className="grid gap-6 md:grid-cols-2">{c.faqs.map(([q, a]) => <div key={q} className="rounded-lg border border-outline-variant bg-surface-container p-6"><h3 className="mb-3 text-headline-md text-on-surface">{q}</h3><p className="text-on-surface-variant">{a}</p></div>)}</div></section><section className="on-ink bg-ink py-24 text-center text-on-ink"><h2 className="mb-4 text-headline-lg">{c.cta}</h2><p className="mx-auto mb-8 max-w-xl text-body-md text-on-ink-variant">{c.ctaText}</p><Link href={`${base}/#contacto`} className="inline-flex min-h-[52px] rounded-md bg-on-ink px-7 py-4 text-base text-ink">{d.common.freeProposal}</Link></section></main><FooterSection lang={params.lang} dict={d.footer} /></>; }
