import type { Metadata } from 'next';
import { PiArrowRight } from 'react-icons/pi';
import Link from 'next/link';
import NavSection from '@/components/sections/section-02-nav';
import FooterSection from '@/components/sections/section-12-footer';
import { buildAlternates, localizedUrl, toLocale } from '@/lib/seo';
import { getDictionary } from '@/dictionaries';

const es = { title: 'Un sistema a medida para dejar de usar planillas', intro: 'Si llevás clientes, ventas o stock en Excel y WhatsApp, te armamos un sistema propio con usuarios, cobros y un panel para ver todo en un solo lugar.', crumb: 'Sistemas Web', capabilitiesTitle: 'Qué puede hacer tu sistema', faq: 'Preguntas frecuentes', cta: '¿Qué parte de tu negocio hoy manejás a mano?', ctaText: 'Contanos qué necesitás construir. Te damos una propuesta concreta en menos de 24 horas.', discuss: 'Discutir mi proyecto', work: 'Ver casos reales', items: [['Tu propia base de datos', 'Guardamos y organizamos la información de tu negocio para que la tengas siempre disponible y ordenada.'], ['Panel de administración', 'Un escritorio a medida para gestionar tu plataforma sin depender de nadie.'], ['Usuarios y permisos', 'Creá cuentas para tu equipo, asigná roles y controlá el acceso al sistema.'], ['Conexiones con otras herramientas', 'Conectamos tu plataforma con Mercado Pago, WhatsApp y los sistemas que ya usás.'], ['Online y a mano', 'Lo usás desde el celular o la compu, en el local o desde tu casa.'], ['Crece con tu negocio', 'Si mañana tenés más clientes o querés sumar una función, el sistema lo aguanta sin rehacerlo.']], faqs: [['¿Cuál es la diferencia entre una landing page y un sistema web?', 'Una landing presenta tu negocio. Un sistema web tiene usuarios, datos guardados y funcionalidades como cobros, reportes o gestión de clientes.'], ['¿Cuánto cuesta desarrollar un sistema web?', 'Desde USD 1.200 para una primera versión funcional. El precio depende del alcance e integraciones.'], ['¿El código es mío?', 'Sí. Te entregamos todo listo para que puedas seguir trabajando con nosotros o con quien elijas.']] } as const;
const en = { title: 'A custom system so you can stop using spreadsheets', intro: 'If you track clients, sales or stock in Excel and WhatsApp, we build you your own system with users, payments and one panel to see everything.', crumb: 'Web Systems', capabilitiesTitle: 'What your system can do', faq: 'Frequently asked questions', cta: 'Which part of your business do you still run by hand?', ctaText: 'Tell us what you need to build. We will send a concrete proposal within 24 hours.', discuss: 'Discuss my project', work: 'View real cases', items: [['Your own database', 'We organize your business information so it is always available and orderly.'], ['Admin panel', 'A custom workspace to manage your platform without depending on anyone.'], ['Users and permissions', 'Create accounts for your team, assign roles and control access.'], ['Connections to other tools', 'Connect your platform with Mercado Pago, WhatsApp and existing systems.'], ['Online and within reach', 'Use it from your phone or computer, at the shop or from home.'], ['Grows with your business', 'If you get more clients tomorrow or want a new feature, the system handles it without a rebuild.']], faqs: [['What is the difference between a landing page and a web system?', 'A landing page presents your business. A web system has users, stored data and features such as payments, reports or customer management.'], ['How much does a web system cost?', 'From USD 1,200 for a first functional version. Price depends on scope and integrations.'], ['Do I own the code?', 'Yes. We hand over everything so you can keep working with us or another team.']] } as const;

export async function generateMetadata({ params }: { params: { lang: string } }): Promise<Metadata> { const locale = toLocale(params.lang); const c = locale === 'en' ? en : es; return { title: `${c.title} | UpCoded`, description: c.intro, alternates: buildAlternates(locale, 'servicios/aplicaciones-web-a-medida'), openGraph: { title: c.title, description: c.intro, url: localizedUrl(locale, 'servicios/aplicaciones-web-a-medida') } }; }

export default async function AplicacionesWebPage({ params }: { params: { lang: 'es' | 'en' } }) {
  const c = params.lang === 'en' ? en : es; const dict = await getDictionary(params.lang); const base = `/${params.lang}`;
  return <><NavSection dict={dict.nav} lang={params.lang} /><main id="contenido" className="pt-[68px]"><section className="mx-auto max-w-container-max px-margin-mobile py-24 md:px-margin-desktop"><nav className="mb-6 flex gap-2 font-mono text-label-caps uppercase text-on-surface-variant"><Link href={base}>{dict.common.home}</Link><span>/</span><Link href={`${base}/#servicios`}>{dict.common.services}</Link><span>/</span><span className="text-primary">{c.crumb}</span></nav><div className="max-w-3xl"><h1 className="mb-6 text-display-lg text-on-surface">{c.title}</h1><p className="mb-8 max-w-2xl text-body-md text-on-surface-variant">{c.intro}</p><div className="flex flex-wrap gap-4"><Link href={`${base}/${params.lang === 'en' ? 'start-project' : 'iniciar-proyecto'}`} className="inline-flex min-h-[52px] items-center gap-2 rounded-md bg-primary px-7 text-base font-medium text-on-primary">{c.discuss}<PiArrowRight size={16} /></Link><Link href={`${base}/#portfolio`} className="inline-flex min-h-[52px] items-center rounded-md border border-outline-strong px-7 text-base text-on-surface">{c.work}</Link></div></div></section><section className="bg-surface-container-low py-24"><div className="mx-auto max-w-container-max px-margin-mobile md:px-margin-desktop"><h2 className="mb-16 text-headline-lg text-on-surface">{c.capabilitiesTitle}</h2><div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">{c.items.map(([title, description]) => <div key={title} className="rounded-lg border border-outline-variant bg-surface-container p-7"><h3 className="mb-2 text-headline-md text-on-surface">{title}</h3><p className="text-on-surface-variant">{description}</p></div>)}</div></div></section><section className="mx-auto max-w-container-max px-margin-mobile py-24 md:px-margin-desktop"><h2 className="mb-16 text-headline-lg text-on-surface">{c.faq}</h2><div className="grid grid-cols-1 gap-6 md:grid-cols-2">{c.faqs.map(([q, a]) => <div key={q} className="rounded-lg border border-outline-variant bg-surface-container p-6"><h3 className="mb-3 text-headline-md text-on-surface">{q}</h3><p className="text-on-surface-variant">{a}</p></div>)}</div></section><section className="on-ink bg-ink py-24 text-on-ink"><div className="mx-auto max-w-container-max px-margin-mobile py-8 text-center md:px-margin-desktop"><h2 className="mb-4 text-headline-lg">{c.cta}</h2><p className="mx-auto mb-8 max-w-xl text-body-md text-on-ink-variant">{c.ctaText}</p><Link href={`${base}/${params.lang === 'en' ? 'start-project' : 'iniciar-proyecto'}`} className="inline-flex min-h-[52px] items-center gap-2 rounded-md bg-on-ink px-7 text-base font-medium text-ink">{dict.common.freeProposal}<PiArrowRight size={16} /></Link></div></section></main><FooterSection lang={params.lang} dict={dict.footer} /></>;
}
